# Site settings
title: bk
email: bk222bh@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This is the portfolio site for Beppe Karlsson.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beppek.me" # the base hostname & protocol for your site
github_username:  beppek

future: true

# Build settings
markdown: kramdown
