# Site settings
title: Beppe Karlsson
email: bk222bh@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  This is the portfolio site for Beppe Karlsson.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  beppek

# Build settings
markdown: kramdown
